### ISSUE TITLE
Gerar mapas (matrizes) 20x20 aleatórias e funcionais!

### ISSUE THREAD

**Issue by Ericles-Porty** [Sinu-Tech/Galeraxxx-Search-Escape#14]
A matriz não pode simplesmente ser gerada aleatoriamente, é preciso uma estratégia para que tenha caminhos válidos.

**Comment by joannestephany** [comment]
Pois não pode ocorrer um labirinto sem saída já que os jogadores serão posicionados aleatoriamente no mapa
